// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WDVA_ECommerce.Server.Data;

#nullable disable

namespace WDVA_ECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230904162324_Categories")]
    partial class Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WDVA_ECommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cups",
                            Url = "cups"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flags",
                            Url = "flags"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Signs",
                            Url = "signs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clothing",
                            Url = "clothing"
                        });
                });

            modelBuilder.Entity("WDVA_ECommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "This Shot Glass makes a perfect gift for any military veteran, active duty soldier, army navy air force, or marine. The perfect shot glass is made of glass and holds 2 oz of liquid, and is perfect for whiskey, vodka, tequila, rum, gin, espresso, or dessert.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Shot_Glass_Gift_b8e35cf871/medium_Shot_Glass_Gift_b8e35cf871.jpg",
                            Price = 10.99m,
                            Title = "Shot Glass"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Get this special travel mug for veteran in your life. This is the perfect gift that they'll appreciate and keep using for his entire life. Make it yourself or give one as a unique gift for someone you know.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Travel_Tumbler_Mug_d4d5e10565/medium_Travel_Tumbler_Mug_d4d5e10565.jpg",
                            Price = 18.99m,
                            Title = "Travel Tumbler Mug"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "The best gift for your loved one is a wood box sign that features the sentiment 'heroes don't wear capes they wear dog tags,' and the design is perfect for you.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Patriotic_Box_Sign_09a27ad5cf/medium_Patriotic_Box_Sign_09a27ad5cf.jpg",
                            Price = 12.99m,
                            Title = "Patriotic Box Sign"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "The perfect gift for any military personnel, this Army Shadow Box is the perfect gift for any service member or anyone who respects those who serve us. It comes in a variety of sizes. The glass of the shadow box will be personalized with your Last Name.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Personalized_Army_Shadow_Box_371ab9833b/medium_Personalized_Army_Shadow_Box_371ab9833b.webp",
                            Price = 35.99m,
                            Title = "Personalized Army Shadow Box"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "This is a natural-looking boulder that's shaped just for you. It's personalized so that it fits perfectly in any setting. This round stone is the perfect addition to your home’s landscaping and your front lawn.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Flag_Landscape_Stone_c3c5791a37/medium_Flag_Landscape_Stone_c3c5791a37.webp",
                            Price = 85.99m,
                            Title = "Flag Landscape Stone"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "This is a fun and unique gift for dads, grandpas, husbands, best dad ever, father's day, fathers day, birthday, valentine's day, mother's day, grandfather's day, birthdays, mothers' day, and other special occasions.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/small_T_Shirt_Veteran_549e4a8960/small_T_Shirt_Veteran_549e4a8960.jpg",
                            Price = 15.25m,
                            Title = "T-Shirt Veteran"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "If you’re looking for the perfect gift for a veteran or any special Marine, give the one who served and served with style by choosing one of these amazing Marine Graduation gifts and Veteran Gifts that feature the best of their military career!",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_USMC_Pint_Glass_ff94bd4a3f/medium_USMC_Pint_Glass_ff94bd4a3f.jpg",
                            Price = 15.25m,
                            Title = "USMC Pint Glass"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "This is must-have wall art! It is a gallery-wrapped canvas that was then custom-built around the artwork using UV-resistant, semi-gloss archival coating that protects the print from fading.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/small_American_Flag_1fa6e1a101/small_American_Flag_1fa6e1a101.jpg",
                            Price = 35.25m,
                            Title = "American Flag"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "This is an amazing piece by the US Army about their soldier's creed! It is the perfect Christmas gift for both current army soldiers and veterans. Each of our steel pieces is carefully cut and polished and uses state-of-the-art equipment to laser etch the piece.",
                            ImgUrl = "https://storage.googleapis.com/loveable.appspot.com/medium_Soldiers_Creed_7ba30f947f/medium_Soldiers_Creed_7ba30f947f.webp",
                            Price = 24.95m,
                            Title = "Soldiers Creed"
                        });
                });

            modelBuilder.Entity("WDVA_ECommerce.Shared.Product", b =>
                {
                    b.HasOne("WDVA_ECommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
